### ISSUE TITLE
manage.py migrate falhando no Heroku

### ISSUE THREAD

**Issue by rougeth** [apyb/associados#246]
```
❯ heroku run python manage.py migrate
Running python manage.py migrate on ⬢ associados... up, run.1788 (Hobby)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, flatpages, members, municipios, payment, sessions, sites, thumbnail
Running migrations:
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying members.0009_pending_migrations_after_django_update... OK
  Applying members.0010_sort_members_by_name... OK
  Applying members.0011_reset_all_passwords...

 OK
  Applying payment.0003_pending_migrations_after_django_update... OK
  Applying thumbnail.0001_initial...Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.ProgrammingError: relation "thumbnail_kvstore" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/app/.heroku/python/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "thumbnail_kvstore" already exists
```

**Comment by rougeth** [comment]
A tabela `thumbnail_kvstore` existe mas está vazia:

```
> select * from thumbnail_kvstore;
+-----+-------+
| key | value |
|-----+-------|
+-----+-------+
SELECT 0
Time: 0.117s
```

**Comment by rougeth** [comment]
Gerei um backup manual do banco (b035), vou deletar essa tabela e rodar a migração novamente.

**Comment by rougeth** [comment]
```
❯ heroku run python manage.py migrate
Running python manage.py migrate on ⬢ associados... up, run.3713 (Basic)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, flatpages, members, municipios, payment, sessions, sites, thumbnail
Running migrations:
  Applying thumbnail.0001_initial... OK

```

**Comment by rougeth** [comment]
Criei uma issue pra remove a biblioteca sorl-thumbnail (responsável por criar a tabela `thumbnail_kvstore`) https://github.com/apyb/associados/issues/254
